from telegram import Update
from telegram.ext import ContextTypes
from core.parser import parse_watch_command
from data.storage import add_watch

async def watch_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    try:
        user_id = update.message.from_user.id
        text = update.message.text

        # The ID is auto-generated by Supabase, so we can just pass 0
        watch = parse_watch_command(user_id, text, 0)

        saved = add_watch(watch)

        await update.message.reply_text(
            f"✅ Alert added for {saved['symbol']} {saved['rule']} {saved['threshold']}"
        )

    except ValueError as e:
        await update.message.reply_text(f"❌ Error: {e}")
    except Exception as e:
        await update.message.reply_text(f"⚠️ Internal error: {e}")
